/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ProxyRPC_H
#define ProxyRPC_H

#include <thrift/TDispatchProcessor.h>
#include "server_types.h"



class ProxyRPCIf {
 public:
  virtual ~ProxyRPCIf() {}
  virtual void getDocument(std::string& _return, const std::string& url) = 0;
};

class ProxyRPCIfFactory {
 public:
  typedef ProxyRPCIf Handler;

  virtual ~ProxyRPCIfFactory() {}

  virtual ProxyRPCIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(ProxyRPCIf* /* handler */) = 0;
};

class ProxyRPCIfSingletonFactory : virtual public ProxyRPCIfFactory {
 public:
  ProxyRPCIfSingletonFactory(const boost::shared_ptr<ProxyRPCIf>& iface) : iface_(iface) {}
  virtual ~ProxyRPCIfSingletonFactory() {}

  virtual ProxyRPCIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(ProxyRPCIf* /* handler */) {}

 protected:
  boost::shared_ptr<ProxyRPCIf> iface_;
};

class ProxyRPCNull : virtual public ProxyRPCIf {
 public:
  virtual ~ProxyRPCNull() {}
  void getDocument(std::string& /* _return */, const std::string& /* url */) {
    return;
  }
};

typedef struct _ProxyRPC_getDocument_args__isset {
  _ProxyRPC_getDocument_args__isset() : url(false) {}
  bool url :1;
} _ProxyRPC_getDocument_args__isset;

class ProxyRPC_getDocument_args {
 public:

  static const char* ascii_fingerprint; // = "EFB929595D312AC8F305D5A794CFEDA1";
  static const uint8_t binary_fingerprint[16]; // = {0xEF,0xB9,0x29,0x59,0x5D,0x31,0x2A,0xC8,0xF3,0x05,0xD5,0xA7,0x94,0xCF,0xED,0xA1};

  ProxyRPC_getDocument_args(const ProxyRPC_getDocument_args&);
  ProxyRPC_getDocument_args& operator=(const ProxyRPC_getDocument_args&);
  ProxyRPC_getDocument_args() : url() {
  }

  virtual ~ProxyRPC_getDocument_args() throw();
  std::string url;

  _ProxyRPC_getDocument_args__isset __isset;

  void __set_url(const std::string& val);

  bool operator == (const ProxyRPC_getDocument_args & rhs) const
  {
    if (!(url == rhs.url))
      return false;
    return true;
  }
  bool operator != (const ProxyRPC_getDocument_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProxyRPC_getDocument_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const ProxyRPC_getDocument_args& obj);
};


class ProxyRPC_getDocument_pargs {
 public:

  static const char* ascii_fingerprint; // = "EFB929595D312AC8F305D5A794CFEDA1";
  static const uint8_t binary_fingerprint[16]; // = {0xEF,0xB9,0x29,0x59,0x5D,0x31,0x2A,0xC8,0xF3,0x05,0xD5,0xA7,0x94,0xCF,0xED,0xA1};


  virtual ~ProxyRPC_getDocument_pargs() throw();
  const std::string* url;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const ProxyRPC_getDocument_pargs& obj);
};

typedef struct _ProxyRPC_getDocument_result__isset {
  _ProxyRPC_getDocument_result__isset() : success(false) {}
  bool success :1;
} _ProxyRPC_getDocument_result__isset;

class ProxyRPC_getDocument_result {
 public:

  static const char* ascii_fingerprint; // = "9A73381FEFD6B67F432E717102246330";
  static const uint8_t binary_fingerprint[16]; // = {0x9A,0x73,0x38,0x1F,0xEF,0xD6,0xB6,0x7F,0x43,0x2E,0x71,0x71,0x02,0x24,0x63,0x30};

  ProxyRPC_getDocument_result(const ProxyRPC_getDocument_result&);
  ProxyRPC_getDocument_result& operator=(const ProxyRPC_getDocument_result&);
  ProxyRPC_getDocument_result() : success() {
  }

  virtual ~ProxyRPC_getDocument_result() throw();
  std::string success;

  _ProxyRPC_getDocument_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const ProxyRPC_getDocument_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ProxyRPC_getDocument_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProxyRPC_getDocument_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const ProxyRPC_getDocument_result& obj);
};

typedef struct _ProxyRPC_getDocument_presult__isset {
  _ProxyRPC_getDocument_presult__isset() : success(false) {}
  bool success :1;
} _ProxyRPC_getDocument_presult__isset;

class ProxyRPC_getDocument_presult {
 public:

  static const char* ascii_fingerprint; // = "9A73381FEFD6B67F432E717102246330";
  static const uint8_t binary_fingerprint[16]; // = {0x9A,0x73,0x38,0x1F,0xEF,0xD6,0xB6,0x7F,0x43,0x2E,0x71,0x71,0x02,0x24,0x63,0x30};


  virtual ~ProxyRPC_getDocument_presult() throw();
  std::string* success;

  _ProxyRPC_getDocument_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

  friend std::ostream& operator<<(std::ostream& out, const ProxyRPC_getDocument_presult& obj);
};

class ProxyRPCClient : virtual public ProxyRPCIf {
 public:
  ProxyRPCClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  ProxyRPCClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void getDocument(std::string& _return, const std::string& url);
  void send_getDocument(const std::string& url);
  void recv_getDocument(std::string& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class ProxyRPCProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<ProxyRPCIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (ProxyRPCProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_getDocument(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  ProxyRPCProcessor(boost::shared_ptr<ProxyRPCIf> iface) :
    iface_(iface) {
    processMap_["getDocument"] = &ProxyRPCProcessor::process_getDocument;
  }

  virtual ~ProxyRPCProcessor() {}
};

class ProxyRPCProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  ProxyRPCProcessorFactory(const ::boost::shared_ptr< ProxyRPCIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< ProxyRPCIfFactory > handlerFactory_;
};

class ProxyRPCMultiface : virtual public ProxyRPCIf {
 public:
  ProxyRPCMultiface(std::vector<boost::shared_ptr<ProxyRPCIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~ProxyRPCMultiface() {}
 protected:
  std::vector<boost::shared_ptr<ProxyRPCIf> > ifaces_;
  ProxyRPCMultiface() {}
  void add(boost::shared_ptr<ProxyRPCIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void getDocument(std::string& _return, const std::string& url) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->getDocument(_return, url);
    }
    ifaces_[i]->getDocument(_return, url);
    return;
  }

};



#endif
